_commit: v1.5.1
_src_path: gh:superlinear-ai/substrate
author_email: chuckie_chen@outlook.com
author_name: Chuckie Chen
project_description: My own scripts to manage source materials
project_name: AssetManager
project_type: app
project_url: https://github.com/chuckieChen945/AssetManager
python_version: "3.12"
typing: strict
with_conventional_commits: true
with_fastapi_api: false
with_typer_cli: true
